### PR TITLE
Fix MultiplyAndAddByModularInteger 

### PR DESCRIPTION
**Pull request by gillenhaalb**
Fixed typo and added clarifications of registers. 

This is used in the coming Learn module (and maybe as the example walk through an API ref page), so would ideally be merged ASAP.

### CODE REVIEW

**Comment by gillenhaalb** [comment]
ping @cgranade

**Review by msoeken — APPROVED** [review]
lgtm. Thanks @gillenhaalb

**Review by cgranade — APPROVED** [review]
Thanks for your patience, looks good to me as well!

**Pull request merged**
