### PR TITLE
Bugfix for RandomReal, added a unit test for it

### PR DESCRIPTION
**Pull request by jclapis**
Hi all,

I'm working with the QDK and noticed a bug with RandomReal. It was generating numbers between 0 and 2, but the documentation says that it should be between 0 and 1. I fixed it here and added a unit test for the RandomReal function as well since it didn't have one.

### CODE REVIEW

**Comment by jclapis** [comment]
@cgranade @vadym-kl 
Hello folks, just checking back on this. Anything you need me to take care of before reviewing?

**Comment by pensono** [comment]
Should the random number generator be seeded so the test is deterministic?

**Comment by anpaz-msft** [comment]
@pensono, there is nothing really random about this test, no need to make the it deterministic.

**Comment by anpaz-msft** [comment]
@jclapis, sorry for the delay. it looks good. merging now and should make it in time for our next release.

**Pull request merged**
