### PR TITLE
Add note: SignedLittleEndian uses two's complement

### LINKED ISSUE #467: How does SignedLittleEndian store negative numbers?
I can guess that it uses two's complement (using Invert2sSI as a hint), but it would be great to say this explicitly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f91b0b-418e-a089-1c94-4b362d905a85
* Version Independent ID: 402c7741-4543-d7c4-6aca-e4f9aadaebbf
* Content: [SignedLittleEndian user defined type - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arithmetic.signedlittleendian)
* Content Source: [api/qsharp/microsoft.quantum.arithmetic.signedlittleendian.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.arithmetic.signedlittleendian.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

### PR DESCRIPTION
**Pull request by tcNickolas**
Fixes #467.

### CODE REVIEW

**Review by msoeken — APPROVED** [review]
Thank you!

**Comment by tcNickolas** [comment]
I don't know how to make GitHub admit it, but the builds passed: https://github.com/microsoft/QuantumLibraries/pull/544/checks?check_run_id=5651823805

**Pull request merged**
