### PR TITLE
Fixes outdated example

### PR DESCRIPTION
**Pull request by RufusJWB**
Fixes https://github.com/microsoft/QuantumLibraries/issues/622

### CODE REVIEW

**Review by msoeken — APPROVED** [review]

**Comment by msoeken** [comment]
Thanks for the contribution @RufusJWB

**Comment by RufusJWB** [comment]
> Thanks for the contribution @RufusJWB

I'm happy that you are offering a way with a low barrier to entry for contributing to your documentation.

**Pull request merged**
