### PR TITLE
Create lexiq

### PR DESCRIPTION
**Pull request by chaos-ui**
can we merge

### CODE REVIEW

**Comment by cgranade** [comment]
Thanks for your contribution, @chaos-ui! Would you be willing to share a bit more context about your PR so that I can review accordingly? Thank you!

**Comment by cgranade** [comment]
Closing in lieu of further context, but please feel free to re-open if you have further details to share about your contribution. Thank you!

**Review by chaos-ui — COMMENTED** [review]
What does this need?

**Review by chaos-ui — COMMENTED** [review]
azure resource made in portal

**Pull request closed without merging**
