### PR TITLE
Fix overestimation in MachineLearning.NQubitsRequired

### LINKED ISSUE #270: MachineLearning.NQubitsRequired overestimates the number of qubits
Sometimes, `Microsoft.Quantum.MachineLearning.NQubitsRequired` function returns bigger number than actually needed. For example, `NQubitsRequired(SequentialModel([ControlledRotation((0, new Int[0]), PauliX, 0), ControlledRotation((0, new Int[0]), PauliY, 0)], [0.0], 0.0))` returns 2, but the correct number is 1.

### PR DESCRIPTION
**Pull request by PhysSong**
Fixes #270.
The function sometimes overestimated the number of required qubits because the `for` loop increased `nQubitsRequired` by 1 when it shouldn't.

### CODE REVIEW

**Comment by PhysSong** [comment]
Sorry for bumping, but any reviews or updates for this?

**Comment by guenp** [comment]
@PhysSong thanks for opening this PR! Apologies for the late reply; I will take a look this afternoon.

**Review by msoeken — APPROVED** [review]
Thanks for this PR @PhysSong

**Pull request merged**
